-- Own dedicated database, plain "notifications" with no schema qualifier —
-- same reasoning as every extracted service's own migrations in this
-- system: this is a single-purpose database, not a shared one split into
-- per-module schemas.
--
-- version (optimistic locking, see common.entity.BaseEntity) included from
-- the start, same convention as every fresh (non-extracted) service's own
-- V1 in this system.

CREATE TABLE notifications (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type                  VARCHAR(30)  NOT NULL,
    channel               VARCHAR(10)  NOT NULL,
    status                VARCHAR(20)  NOT NULL DEFAULT 'PENDING',
    customer_id           BIGINT       NOT NULL,
    recipient_address     VARCHAR(255) NOT NULL,
    order_id              BIGINT,
    provider_name         VARCHAR(50),
    provider_message_id   VARCHAR(255),
    sent_at               TIMESTAMP(6),
    retry_count           INT          NOT NULL DEFAULT 0,
    last_error            TEXT,
    version               BIGINT       NOT NULL DEFAULT 0,
    created_at            TIMESTAMP(6) NOT NULL,
    updated_at            TIMESTAMP(6) NOT NULL,
    CONSTRAINT ck_notifications_type CHECK (type IN (
        'ORDER_CONFIRMED', 'ORDER_CANCELLED', 'PAYMENT_CONFIRMED', 'PAYMENT_FAILED',
        'SHIPMENT_SHIPPED', 'SHIPMENT_DELIVERED', 'SHIPMENT_RETURNED', 'CUSTOMER_WELCOME'
    )),
    CONSTRAINT ck_notifications_channel CHECK (channel IN ('EMAIL', 'SMS', 'PUSH')),
    CONSTRAINT ck_notifications_status CHECK (status IN ('PENDING', 'SENT', 'FAILED', 'DEAD_LETTERED'))
);

CREATE INDEX idx_notifications_customer_id ON notifications (customer_id);
CREATE INDEX idx_notifications_status ON notifications (status);
CREATE INDEX idx_notifications_order_id ON notifications (order_id);
