-- Per-(customer, notification type, channel) opt-in state — see
-- notification.entity.NotificationPreference's own Javadoc. Included in
-- Phase 1's schema even though the enforcement UI/API for changing a
-- preference isn't built yet (see this service's README) — the plan this
-- service was scoped from is explicit that retrofitting opt-out after
-- notifications are already flowing to real customers is the wrong order,
-- so the table exists now even though nothing writes to it yet outside a
-- direct DB write or the (not-yet-built) preference endpoints.

CREATE TABLE notification_preferences (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id         BIGINT       NOT NULL,
    notification_type   VARCHAR(30)  NOT NULL,
    channel             VARCHAR(10)  NOT NULL,
    opted_in            BOOLEAN      NOT NULL DEFAULT TRUE,
    version             BIGINT       NOT NULL DEFAULT 0,
    created_at          TIMESTAMP(6) NOT NULL,
    updated_at          TIMESTAMP(6) NOT NULL,
    CONSTRAINT uq_notification_preferences_customer_type_channel
        UNIQUE (customer_id, notification_type, channel),
    CONSTRAINT ck_notification_preferences_type CHECK (notification_type IN (
        'ORDER_CONFIRMED', 'ORDER_CANCELLED', 'PAYMENT_CONFIRMED', 'PAYMENT_FAILED',
        'SHIPMENT_SHIPPED', 'SHIPMENT_DELIVERED', 'SHIPMENT_RETURNED', 'CUSTOMER_WELCOME'
    )),
    CONSTRAINT ck_notification_preferences_channel CHECK (channel IN ('EMAIL', 'SMS', 'PUSH'))
);

CREATE INDEX idx_notification_preferences_customer_id ON notification_preferences (customer_id);
